- name: Update alle fedora systemen
  hosts: fedora
  become_user: root
  tasks:
    - name: Ping
      ansible.builtin.ping:
    - name: Update all packages
      raw: /usr/bin/dnf -y upgrade
    - name: Check if a reboot is needed
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no
    - name: Reboot the server
      reboot:
        msg: "Reboot initiated by Ansible due to kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists