- name: Update all debian/ubuntu systems
  tasks:
    - name: Ping
      hosts: all:~unraid
      ansible.builtin.ping:
    - name: Ping unraid
      hosts: unraid
      user: root
      ansible.builtin.ping: