# Clone repository
# Run build script
# Docker container
# Push naar registry
# Discord notification
# remove build files
- name: Build ibs3 container
  hosts: build
  vars:
    branch: "main"
    repository_link: "https://github.com/ODDInvictus/ibs3"
    build_path: "~/build/ibs3/main"
  tasks:
    - name: Create build directory
      file:
        path: "{{ build_path }}"
        state: directory
        mode: '0755'

    - name: Clone git repository
      ansible.builtin.git:
        repo: "{{ repository_link }}"
        dest: "{{ build_path }}"
        single_branch: yes
        version: "{{ branch }}"

    # - name: NPM install
    #   community.general.npm:
    #     path: "{{ build_path }}"
    #     ci: true

    - name: Run build script
      command:
        chdir: "{{ build_path }}"
        cmd: npm run build
      environment:
        # De build heeft toegang nodig tot een werkende database (...?)
        # De bug zit ergens in de form generator oef
        # Deze komt uit semaphore
        DATABASE_URL: "{{ DATABASE_URL }}"

    - name: Build docker image
      docker_image:
        name: ibs3:test1
        build:
          dockerfile: "new.Dockerfile"
          path: "{{ build_path }}"
        source: build

