# Maintenance mode
# Oude ibs3 container afsluiten
# Backup database
# Run migrations
# Run data-migrations
# Nieuwe container deployen
# geen errors? Dan maintenance mode eraf
# anders, backup terugzetten
# oude container terugzetten
- name: Deploy ibs3
  hosts: build
  vars:
    caddy_1: "/config/apps/http/servers/srv0/routes/"
    caddy_2: "/handle/0/routes/0/handle/0/upstreams/0"
  tasks:
    - name: debug
      debug:
        msg: "{{ caddy_url }}{{ caddy_1 }}{{ ibs3_server_id }}{{ caddy_2 }} {{ ibs3_maintenance_url }}"

    - name: Maintenance mode
      shell: "curl -X PATCH -H \"Content-Type: application/json\" -d \"{ \\\"dial\\\": \\\"{{ ibs3_maintenance_url }}\\\" }\" -i {{ caddy_url }}{{ caddy_1 }}{{ ibs3_server_id }}{{ caddy_2 }}"
      # ansible.builtin.uri:
        # url: "{{ caddy_url }}{{ caddy_1 }}{{ ibs3_server_id }}{{ caddy_2 }}"
        # method: "PATCH"
        # body_format: json
        # body: "{ \"dial\": \"{{ ibs3_maintenance_url }}\" }"
        # status_code: 200
        # timeout: 10

    - name: debug
      debug:
        msg: "{{ caddy_url }}{{ caddy_1 }}{{ ibs3_server_id }}{{ caddy_2 }}"
