# Maintenance mode
# Oude ibs3 container afsluiten
# Backup database
# Run migrations
# Run data-migrations
# Nieuwe container deployen
# geen errors? Dan maintenance mode eraf
# anders, backup terugzetten
# oude container terugzetten
- name: Deploy ibs3
  hosts: build
  gather_facts: false
  vars:
    caddy_1: "/config/apps/http/servers/srv0/routes/"
    caddy_2: "/handle/0/routes/0/handle/0/upstreams/0"
  tasks:
    - name: maintenance mode
      maxhoesel.caddy.caddy_config:
        caddy_host: "{{ caddy_url }}"
        path: "/apps/http/servers/srv0/routes/{{ ibs3_server_id }}/handle/0/routes/0/handle/0/upstreams/0"
        content:
          dial: "{{ ibs3_maintenance_url }}"
        state: present
        force: true
