- name: Music server
  hosts: music
  
  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Add spocon repository
      apt_repository:
        repo: ppa:spocon/spocon
        state: present

    - name: Install spocon
      apt:
        name: spocon
        state: latest