- name: Music server
  hosts: music
  become: true
  become_user: root
  roles:
    - role: xmordax.librespot
  
  vars:
    librespot_installation_type: "librespot-java"
    raspotify_device_name: "Make Believe"